---
stitle: "sp_analysis"
author: "Yixin (Izzy) Zhang"
date: "2024-08-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
```

## Process data

```{r, echo = False}
source("data_cleaning_sp.R")

clean_all_trials <- function(folder_name) {
  raw_files <- list.files(folder_name, pattern = "test\\d+\\.txt$", full.names = TRUE)
  for (file in raw_files) {
    clean_file(file)
  }
}
# clean_all_trials("../data/P1")
```

```{r}
analyze_all_trials <- function(folder_name) {
  cleaned_files <- list.files(folder_name, pattern = "test\\d+\\_cleaned.csv$", full.names = TRUE)
  data_summary <- data.frame(
    min_velocity = numeric(), 
    max_velocity = numeric(), 
    mean_angle = numeric(), 
    sd_angle = numeric()
  )
  i = 1
  for (file in cleaned_files) {
    data <- read.csv(file)
    data <- data[2500:(nrow(data) - 2500 + 1), ] # remove first and last 5s
    # hist(data$angular_velocity, main = paste(file, "velocity histogram"))
    data_summary[i, 1] <- min(data$angular_velocity)
    data_summary[i, 2] <- max(data$angular_velocity)
    data_summary[i, 3] <- mean(data$APAngle.deg.)
    data_summary[i, 4] <- sd(data$APAngle.deg.)
    print(paste("processed ", file))
    i <- i + 1
  }
  return(data_summary)
}
```

```{r}
process_all_trials <- function(folder_name){
  clean_all_trials(folder_name)
  analyze_all_trials(folder_name)
}

```

```{r}
remove_5s <- function(file){
  data <- read.csv(file)
  data <- data[2500:(nrow(data) - 2500 + 1), ]
  return(data)
}
combine_data <- function(folder_name) {
  cleaned_files <- list.files(folder_name, pattern = "test\\d+_cleaned.csv$", full.names = TRUE)
  combined_df <- do.call(rbind, lapply(cleaned_files, remove_5s))
  return(combined_df)
}

```

```{r}
Amin <- process_all_trials("../data/P1")
Izzy <- process_all_trials("../data/P2")
JS <- process_all_trials("../data/P3")
Spencer <- process_all_trials("../data/P4")
Calvin <- process_all_trials("../data/P5")

P1_comb <- combine_data("../data/P1")
P2_comb <- combine_data("../data/P2")
P3_comb <- combine_data("../data/P3")
P4_comb <- combine_data("../data/P4")
P5_comb <- combine_data("../data/P5")
```


```{r}
mean(P1_comb$APAngle.deg.)
mean(Amin$mean_angle)
sd(P1_comb$APAngle.deg.)
mean(Amin$sd_angle)
```
```{r}
min(P1_comb$angular_velocity)
max(P1_comb$angular_velocity)
sd(P1_comb$angular_velocity)
```


```{r}
all_datasets <- list(P1_comb, P2_comb, P3_comb, P4_comb, P5_comb)
sep_datasets <- list(Amin, Izzy, JS, Spencer, Calvin)

calculate_summary <- function(all_data, sep_data) {
  mean_all <- mean(all_data$APAngle.deg.)
  mean_mean <- mean(sep_data$mean_angle)
  sd_mean <- sd(sep_data$mean_angle)
  mean_sd <- mean(sep_data$sd_angle)
  sd_all <- sd(all_data$APAngle.deg.)

  min_all_vel <- min(all_data$angular_velocity)
  max_all_vel <- max(all_data$angular_velocity)
  sd_all_vel <- sd(all_data$angular_velocity)
  
  return(data.frame(
    avg_everything = mean_all,
    avg_setpoints = mean_mean,
    sd_setpoints = sd_mean,
    avg_sd = mean_sd, 
    sd_everything = sd_all,
    min_all_vel = min_all_vel,
    max_all_vel = max_all_vel,
    sd_all_vel = sd_all_vel
  ))
}

summary_tables <- lapply(1:5, function(i) {
  calculate_summary(all_datasets[[i]], sep_datasets[[i]])
})

final_summary <- do.call(rbind, summary_tables)
subject_ids <- c('P1', 'P2', 'P3', 'P4', 'P5')
final_summary <- cbind(subject_ids = subject_ids, final_summary)

print(final_summary)
```

```{r}
mean(final_summary$max_all_vel)
```

